# Use python:alpine3.7 for the base image
FROM python:alpine3.7

# Copy the .py files in ./app from build's context to /app
COPY
# Copy the Pipfile in ./app from build's context to /app

# Change the working directory to WORKDIR

# Install bind-tools

# Install pipenv

# Install the environment

# Expose port 8080

# Start the python application
